name: Tests Run
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Generate Artfacts
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        with:
          name: cypress-reports
          path: cypress/reports/html
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Matheus Oliveira"
          SLACK_TITLE: "Testando Anexo de artefatos"
          SLACK_MESSAGE: "Deu Certo!!!"
